const home = {
    overviewArr: state => state.home.overviewArr,
    overviewTrendArr: state => state.home.overviewTrendArr,
    productArr: state => state.home.productArr,
    productTrendArr: state => state.home.productTrendArr,
    channelArr: state => state.home.channelArr,
    channelTrendArr: state => state.home.channelTrendArr,
    orgHomeArr: state => state.home.orgHomeArr,
    orgTrendArr: state => state.home.orgTrendArr,
    fundHomeArr: state => state.home.fundHomeArr,
    fundHomeTrendArr: state => state.home.fundHomeTrendArr,
    cusHomeArr: state => state.home.cusHomeArr,
    cusHomeTrendArr: state => state.home.cusHomeTrendArr,
    searchDate: state => state.home.searchDate,
    homeLastParams: state => state.home.homeLastParams,
    salePrograssArr: state => state.home.salePrograssArr,
    saleTrendArr: state => state.home.saleTrendArr,
    profitPrograssArr: state => state.home.profitPrograssArr,
    profitTrendArr: state => state.home.profitTrendArr,
    gainPrograssArr: state => state.home.gainPrograssArr,
    gainTrendArr: state => state.home.gainTrendArr,
    payPrograssArr: state => state.home.payPrograssArr,
    payTrendArr: state => state.home.payTrendArr,
    abilityPrograssArr: state => state.home.abilityPrograssArr,
    abilityTrendArr: state => state.home.abilityTrendArr,
    brandPrograssArr: state => state.home.brandPrograssArr,
    brandTrendArr: state => state.home.brandTrendArr,
};

export default home;
